SPACE repeatable playlist-next
alt+SPACE repeatable playlist-prev

UP ignore
DOWN ignore
LEFT repeatable playlist-prev
RIGHT repeatable playlist-next

+ add video-zoom 0.1
- add video-zoom -0.1
0 no-osd set video-zoom 0

h no-osd vf toggle hflip; show-text "Horizontal flip"
v no-osd vf toggle vflip; show-text "Vertical flip"

r script-message rotate-video 90; show-text "Clockwise rotation"
R script-message rotate-video -90; show-text "Counter-clockwise rotation"
alt+r no-osd set video-rotate 0; show-text "Reset rotation"
