# mpv.conf

vo=gpu-next
ao=null

cache=no
osc=no
sub-auto=no
ytdl=no

scale=spline36
cscale=spline36
dscale=mitchell
dither-depth=auto
correct-downscaling
sigmoid-upscaling
video-unscaled=downscale-big

background=color
background-color=0.1

image-display-duration=inf
loop-file=inf
loop-playlist=inf

window-dragging=no

[extension.png]
video-aspect-override=no

[extension.jpg]
video-aspect-override=no

[extension.jpeg]
profile=extension.jpg
