#!/bin/bash

if pgrep wlsunset; then
    pkill wlsunset
else
    data=$(curl -s -m3 http://ip-api.com/json/)
    cache=~/.cache/wlsunset-toggle
    [[ "$data" ]] && echo $data > $cache

    wlsunset $(cat $cache | jq -r '"-L \(.lon) -l \(.lat)"')
fi
