#!/bin/bash

if pid=$(pgrep -x wlsunset); then
    kill $pid
else
    data=$(curl -s -m3 http://ip-api.com/json/)
    cache=~/.cache/wlsunset-toggle.json
    [[ "$data" ]] && echo $data > $cache

    wlsunset $(cat $cache | jq -r '"-L \(.lon) -l \(.lat)"')
fi
