|202|Firefox Web Browser|firefox
|244|LibreOffice        |libreoffice
| 71|LibreOffice Calc   |libreoffice --calc
|172|LibreOffice Draw   |libreoffice --draw
| 25|LibreOffice Writer |libreoffice --writer
|  8|Terminal Emulator  |x-terminal-emulator
