SPACE repeatable playlist-next
alt+SPACE repeatable playlist-prev

LEFT repeatable playlist-prev
RIGHT repeatable playlist-next
UP ignore
DOWN ignore

alt+= repeatable add video-zoom 0.1
alt+LEFT  repeatable add video-pan-x  0.01
alt+RIGHT repeatable add video-pan-x -0.01
alt+UP    repeatable add video-pan-y  0.01
alt+DOWN  repeatable add video-pan-y -0.01

alt+shift+LEFT  script-message align left
alt+shift+RIGHT script-message align right
alt+shift+UP    script-message align top
alt+shift+DOWN  script-message align bottom

a cycle-values scale spline36 nearest ewa_lanczossharp; show-text "scale: ${scale}"

h vf toggle hflip
v vf toggle vflip

r repeatable cycle-values video-rotate 90 180 270 0
R repeatable cycle-values video-rotate 270 180 90 0
alt+r set video-rotate 0

s script-message reset-view; cycle-values video-unscaled downscale-big no yes
